version: 2.1

commands:
  config_git_user:
    description: 'Configure git user'
    steps:
      - run: git config user.name "$GIT_NAME"
      - run: git config user.email "$GIT_EMAIL"

  install:
    description: 'Install packages'
    steps:
      - checkout
      - run:
          name: 'Update NPM'
          command: sudo npm install -g npm@latest
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
      - run:
          name: 'Install NPM'
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

  run_tests:
    description: 'Run tests'
    steps:
      - run:
          name: 'Run tests'
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  build:
    description: 'Build the bundle'
    steps:
      - run: npm run build
      - save_cache:
          key: repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - ./dist
            - ./package.json

  authenticate:
    description: 'Authenticate with registry'
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc

  publish_beta:
    description: 'Publish beta version to npmjs'
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Revision }}
      - run:
          name: 'Publish package'
          command: npm run publish:beta

  publish:
    description: 'Publish to npmjs'
    steps:
      - restore_cache:
          keys:
            - repo-{{ .Branch }}-{{ .Revision }}
      - run:
          name: 'Publish package'
          command: npm run publish

  build_story:
    description: 'Build storybook'
    steps:
      - run: npm run build-storybook

  deploy_story:
    description: 'Deploy storybook'
    steps:
      - run: npm run deploy-storybook

jobs:
  build:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/react-simple-tree-menu
    steps:
      - install
      - run_tests
      - build_story
      - build

  release_beta:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/react-simple-tree-menu
    steps:
      - authenticate
      - publish_beta

  release:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/react-simple-tree-menu
    steps:
      - authenticate
      - publish

workflows:
  version: 2.
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*)?(\+[0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*)?$/
            branches:
              ignore: /.*/
      - release_beta:
          requires:
            - build
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)-(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*$/
            branches:
              ignore: /.*/
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/
            branches:
              ignore: /.*/
